#!/bin/sh
export POSIXLY_CORRECT=yes

print_help(){
    echo HELP
    echo corona - COVID-19 data analyzer
    echo corona - [-h] [FILTERS] [COMMAND] [LOG [LOG2 [...]]]
    echo
    echo COMMANDS:
    echo    infected - counts number of infected
    echo    merge - unites multiple files into one "(original order will be maintained)"
    echo    gender - return amount of infected for both genders
    echo    age - returns data for various age groups
    echo    daily - returns data for specific days
    echo    monthly - returns data for specific months
    echo    yearly - returns data for specifc years
    echo    countries - returns data for various countries "(excluding Czech Republic)"

}

infected(){
    echo  "$FILTERED" | awk   -v count=0 '{count++} END {print count}'
    exit 0
}

gender(){
    if [ $FILTER_WIDTH == "NOTHING" ];then
        echo  "$FILTERED" | awk -F ',' -v count=0 '/,M,/ {count++} END {print "M: " count}'
        echo  "$FILTERED" | awk -F ',' -v count=0 '/,Z,/ {count++} END {print "Z: " count}'
    elif [ $FILTER_WIDTH == "CLASSIC" ]; then
        echo "$FILTERED" | sort -t, -k4,4 | awk -F ',' -v count=1 -v  width=100000 '/,M,/ {count++}\
        END {printf("M: ")}\
        END {for (i=0; i < count/width-1; i++)\
        printf("#") }\
        END {printf("\n")}'

        echo "$FILTERED" | sort -t, -k4,4 | awk -F ',' -v count=1 -v  width=100000 '/,Z,/ {count++}\
        END {printf("Z: ")}\
        END {for (i=0; i < count/width-1; i++)\
        printf("#") }\
        END {printf("\n")}'
    else
        echo "$FILTERED" | sort -t, -k4,4 | awk -F ',' -v count=0 -v  width="$FILTER_WIDTH" '/,M,/ {count++}\
        END {printf("M: ")}\
        END {for (i=0; i < count/width; i++)\
        printf("#") }\
        END {printf("\n")}'

        echo "$FILTERED" | sort -t, -k4,4 | awk -F ',' -v count=0 -v  width="$FILTER_WIDTH" '/,Z,/ {count++}\
        END {printf("Z: ")}\
        END {for (i=0; i < count/width; i++)\
        printf("#") }\
        END {printf("\n")}'

    fi

}

daily(){
    echo "$FILTERED" | sort -t, -k2,2 | awk -F ',' 'BEGIN{
    day = ""
    daySum = 1
    }{
    if (day== ""){
        day = $2
    }
    else if (day == $2)
    {
        daySum++
    }
    else
    {
        printf("%s :%d\n", day, daySum)
        daySum = 1
        day=$2
    }}
    END{printf("%s: %d\n", day, daySum)}'
}

monthly(){
    echo "$FILTERED" | sort -t, -k2,2 | awk -F ',' 'BEGIN{
    month = ""
    monthSum = 1
    }{
    if (month== ""){
        month = substr($2 ,1, 7)
    }
    else if (month == substr($2 ,1, 7))
    {
        monthSum++
    }
    else
    {
        printf("%s :%d\n", month, monthSum)
        monthSum = 1
        month = substr($2 ,1 ,7)
    }}
    END{printf("%s :%d\n", month, monthSum)}'
}

yearly(){
    echo "$FILTERED" | sort -t, -k2,2 | awk -F ',' 'BEGIN{
    year = ""
    yearSum = 1
    }{
    if (year== ""){
        year = substr($2 ,1, 4)
    }
    else if (year == substr($2 ,1, 4))
    {
        yearSum++
    }
    else
    {
        printf("%s :%d\n", year, yearSum)
        yearSum = 1
        year = substr($2 ,1 ,4)
    }}
    END{printf("%s :%d\n", year, yearSum)}'
}



FILES=""
FILTER_GENDER=""
FILTER_DATE_A="0000-00-00"
FILTER_DATE_B="9999-00-00"
FILTER_WIDTH="NOTHING"
COMMAND="NOTHING"
RE="^[0-9]+$"

while [ "$#" -gt 0 ]; do
    case "$1" in

    infected | merge | gender | age | daily | monthly | yearly | countries | districts | regions)
        COMMAND="$1"
        shift
        ;;

    -h)
        print_help
        exit 0
        ;;

    -s)
        if ! [[ "$2" =~ ^[0-9]+$ ]]
        then
            FILTER_WIDTH="CLASSIC"
            shift
        else
            FILTER_WIDTH="$2"
            shift
            shift
        fi
        ;;

    -g)
        if [ "$2" == "Z" ]; then
            FILTER_GENDER="$2"
        fi
        if [ "$2" == "M" ]; then
            FILTER_GENDER="$2"
        fi
        shift
        shift
        ;;

    -a)
        FILTER_DATE_A="$2 $FILTER_DATE"
        shift
        shift
        ;;

    -b)
        FILTER_DATE_B="$2"
        shift
        shift
        ;;

    *)
        FILES="$1 $FILES"
        shift
        ;;

    esac
done
#echo "$COMMAND"
#---------------------------------------------------------FILTERING-----------------------------------------------------------
READ_FILES=$(cat $FILES)

#FILTERING DATE
FILTERED=$(echo "$READ_FILES" | awk -F ',' -v dateA="$FILTER_DATE_A" -v dateB="$FILTER_DATE_B" '{if($2 > dateA && $2< dateB) {print }}')

#FILTERING GENDER
if [ "$FILTER_GENDER" == "M" ]; then
    FILTERED=$(echo "$FILTERED"| awk -F "," '/,M,/ {print}')
fi
if [ "$FILTER_GENDER" == "Z" ]; then
    FILTERED=$(echo "$FILTERED"| awk -F "," '/,Z,/ {print}')
fi
FILTERED="id,datum,vek,pohlavi,kraj_nuts_kod,okres_lau_kod,nakaza_v_zahranici,nakaza_zeme_csu_kod,reportovano_khs
"$FILTERED
#-----------------------------------------------------CHECKING COMMANDS-------------------------------------------------------
#no need to check commands if no were given
if [ $COMMAND == "NOTHING" ]; then
    echo "$FILTERED"
    exit 0
fi

#INFECTED
if [ $COMMAND == "infected" ]; then
    infected
    exit 0
fi

#GENDER
if [ $COMMAND == "gender" ]; then
    gender
    exit 0
fi

#DAILY
if [ $COMMAND == "daily" ]; then
    daily
    exit 0
fi

if [ $COMMAND == "yearly" ]; then
    yearly
    exit 0
fi



if [ $COMMAND == "monthly" ]; then
    echo "$FILTERED" | sort -t, -k2,2 | awk -F ',' 'BEGIN{
    month = ""
    monthSum = 1
    }{
    if (month== ""){
        month = substr($2 ,1, 7)
    }
    else if (month == substr($2 ,1, 7))
    {
        monthSum++
    }
    else
    {
        printf("%s :%d\n", month, monthSum)
        monthSum = 1
        month = substr($2 ,1 ,7)
    }}
    END{printf("%s :%d\n", month, monthSum)}'
fi

if [ $COMMAND == "age" ]; then
    echo "$FILTERED" | awk -F ',' 'BEGIN{
    sum5=0
    sum15=0
    sum25=0
    sum35=0
    sum45=0
    sum55=0
    sum65=0
    sum75=0
    sum85=0
    sum95=0
    sum105=0
    sumMore=0
    None=0
    }{
    if ($3 < 6){
        sum5++
    }
    else if($3 > 5 && $3 < 16){
    sum15++
    }
    else if($3 > 15 && $3 < 26){
    sum25++
    }
    else if($3 > 25 && $3 < 36){
    sum35++
    }
    else if($3 > 35 && $3 < 46){
    sum45++
    }
    else if($3 > 45 && $3 < 56){
    sum55++
    }
    else if($3 > 55 && $3 < 66){
    sum65++
    }
    else if($3 > 65 && $3 < 76){
    sum75++
    }
    else if($3 > 75 && $3 < 86){
    sum85++
    }
    else if($3 > 85 && $3 < 96){
    sum95++
    }
    else if($3 > 95 && $3 < 106){
    sum105++
    }
    else if($3 > 105){
    sumMore++
    }
    else{
    None++
    }}
    END{
    printf("0-5   : %d\n",sum5 )
    printf("6-15  : %d\n",sum15 )
    printf("16-25 : %d\n",sum25 )
    printf("26-35 : %d\n",sum35 )
    printf("36-45 : %d\n",sum45 )
    printf("46-55 : %d\n",sum55 )
    printf("56-65 : %d\n",sum65 )
    printf("66-75 : %d\n",sum75 )
    printf("76-85 : %d\n",sum85 )
    printf("86-95 : %d\n",sum95 )
    printf("96-105: %d\n",sum105 )
    printf(">105  : %d\n",sumMore )
    printf("None  : %d\n",None )

    }
    '
    exit 0
fi

#echo "$FILTERED"

